import "bootstrap/dist/css/bootstrap.css";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import HandlingBootstrapJs from "@/components/Handling bootstrap js/handling";
import GetLocationCurrentUser from "@/components/Get info location current user/getLocation";
import styles from "./_page.module.scss";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GetLocationCurrentUser>
          <Navbar />
          <div
            className={styles.mainDivInLayout}
            style={{
              paddingTop: "25px",
            }}
          >
            {children}
            <HandlingBootstrapJs />
          </div>
        </GetLocationCurrentUser>
        <Footer />
      </body>
    </html>
  );
}
